#version 460
#extension GL_EXT_buffer_reference : require

#include "bufferInfo.glsl"

layout(set = 0, binding = 0) uniform UBO 
{
	vec4 frustumPlanes[6];
} ubo;	

layout(push_constant) uniform pushConstant
{
    OutputIndirectDraws drawBufferAddress;
	RenderCallBuffer renderCallBuff;
	int numDraws;
} pc;

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

bool frustumCheck(vec3 min, vec3 max)
{
	for (int i = 0; i < 6; i++) {
		int num = 0;
		num += ((dot(ubo.frustumPlanes[i], vec4(min.x, min.y, min.z, 1.0f)) < 0.0) ? 1 : 0);
		num += ((dot(ubo.frustumPlanes[i], vec4(max.x, min.y, min.z, 1.0f)) < 0.0) ? 1 : 0);
		num += ((dot(ubo.frustumPlanes[i], vec4(min.x, max.y, min.z, 1.0f)) < 0.0) ? 1 : 0);
		num += ((dot(ubo.frustumPlanes[i], vec4(max.x, max.y, min.z, 1.0f)) < 0.0) ? 1 : 0);
		num += ((dot(ubo.frustumPlanes[i], vec4(min.x, min.y, max.z, 1.0f)) < 0.0) ? 1 : 0);
		num += ((dot(ubo.frustumPlanes[i], vec4(max.x, min.y, max.z, 1.0f)) < 0.0) ? 1 : 0);
		num += ((dot(ubo.frustumPlanes[i], vec4(min.x, max.y, max.z, 1.0f)) < 0.0) ? 1 : 0);
		num += ((dot(ubo.frustumPlanes[i], vec4(max.x, max.y, max.z, 1.0f)) < 0.0) ? 1 : 0);
		if (num == 8) return false;
    }
	return true;
}

void main()
{
   	uint idx = gl_GlobalInvocationID.x;

	if (idx >= pc.numDraws) {
		return;
    }

	RenderCall r = pc.renderCallBuff.calls[idx];

	vec3 currentMin = (r.instanceMatrix * vec4(r.aabbMin, 1.0)).xyz;
	vec3 currentMax = (r.instanceMatrix * vec4(r.aabbMax, 1.0)).xyz;

   	if (frustumCheck(currentMin, currentMax)) 
	{
		pc.drawBufferAddress.indirectDrawsOut[idx].instanceCount = 1; // if visible, set the draw instance count to 1
	}
	else{
		pc.drawBufferAddress.indirectDrawsOut[idx].instanceCount = 0; // if not visible, set the draw instance count to 0
	}
}